INSERT INTO "TURMA" (ID, VERSION, NAME) VALUES
(1, 1, 'PRIMEIRO ANO'),
(2, 1, 'SEGUNDO ANO'),
(3, 1, 'TERCEIRO ANO');

INSERT INTO "SERIE" (ID, VERSION, NAME) VALUES
(4, 1, 'A'),
(5, 1, 'B'),
(6, 1, 'C');

